'use client'

import { useState } from 'react'
import type { AnsweredQuestion } from '@/types'
import { buildClaudePrompt } from '@/lib/claudePrompt'
import { hasAnyExplanation } from './Provenance'

export default function ClaudeCTA({ answered }: { answered: AnsweredQuestion }) {
  const [copied, setCopied] = useState(false)

  const copy = async () => {
    const prompt = buildClaudePrompt(answered)
    try {
      await navigator.clipboard.writeText(prompt)
    } catch {
      // Fallback for browsers without clipboard API access
      const ta = document.createElement('textarea')
      ta.value = prompt
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  const q = answered.question
  const verify = hasAnyExplanation(q) // explanation exists but AI → double-check

  return (
    <div
      className="card"
      style={{
        marginBottom: '1.25rem',
        background: 'rgba(221, 203, 245, 0.06)',
        borderColor: 'rgba(221, 203, 245, 0.18)',
      }}
    >
      <div
        style={{
          fontSize: 10,
          fontWeight: 700,
          color: 'var(--lavender)',
          textTransform: 'uppercase',
          letterSpacing: '0.07em',
          marginBottom: 8,
        }}
      >
        {verify ? 'Double-check with Claude' : 'No saved explanation'}
      </div>
      <p
        style={{
          fontSize: 13,
          color: 'var(--text-muted)',
          lineHeight: 1.6,
          marginBottom: 12,
        }}
      >
        {verify
          ? 'This answer/explanation was generated by AI and is not from an official key. Copy a ready-made prompt and paste it into the Claude app to verify it.'
          : 'This question has no recorded answer or explanation yet. Copy a ready-made prompt and paste it into the Claude app to get a full explanation.'}
      </p>
      <button
        type="button"
        onClick={copy}
        className="btn btn-primary"
        style={{ height: 40, fontSize: 13 }}
      >
        {copied
          ? '✓ Copied — paste into Claude'
          : verify
            ? 'Verify with Claude'
            : 'Explain with Claude'}
      </button>
    </div>
  )
}
